shop/cart/urls.py
from django.urls import path

from .views import (OrderCreate, OrderDetail, OrderList, VirtualOrderCreate,
                    call_back, cart_add, cart_detail, cart_remove,
                    comparison_add, comparison_detail, comparison_remove,
                    favorites_add, favorites_detail, favorites_remove)

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('comparison/', comparison_detail, name='comparison_detail'),
    path('favorites/', favorites_detail, name='favorites_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('comparison_add/<int:product_id>/', comparison_add, name='comparison_add'),
    path('favorites_add/<int:product_id>/', favorites_add, name='favorites_add'),
    path('comparison_remove/<int:product_id>/', comparison_remove, name='comparison_remove'),
    path('favorites_remove/<int:product_id>/', favorites_remove, name='favorites_remove'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
    path('orderoneclick/', VirtualOrderCreate.as_view(), name='virtual_order'),
    path('order/', OrderCreate.as_view(), name='order'),
    path('orderdetail/<int:pk>/', OrderDetail.as_view(), name='order_detail'),
    path('order_list/', OrderList.as_view(), name='order_list'),
    path('call-back/', call_back, name='call_back')
]

shop/main/urls.py
from django.urls import path

from .views import (CatalogView, CategoryList, Main_page, ProductDetailView,
                    ReviewCreate, ReviewList, SearchListView)

app_name = 'main'

urlpatterns = [
    path('', Main_page.as_view(), name='main_page'),
    path('category/', CategoryList.as_view(), name='category'),
    path('category/<int:pk>', CatalogView.as_view(), name='catalog'),
    path('product/<int:pk>', ProductDetailView.as_view(), name='productdetail'),
    path('review/<int:pk>', ReviewList.as_view(), name='review'),
    path('reviewcreate/<int:pk>', ReviewCreate.as_view(), name='reviewcreate'),
    path('search/', SearchListView.as_view(), name='search')
]

shop/shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('account.urls')),
    path('api/', include('rest_api.urls')),
    path('cart/', include('cart.urls')),
    path('', include('main.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/cart/models.py
from django.db import models

# Create your models here.

shop/main/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse


class Profile(AbstractUser):
    phone = models.IntegerField(unique=True, null=True)
    address = models.CharField(max_length=250, null=True, blank=True)
    send_message = models.BooleanField(default=False)


class Shop(models.Model):
    city = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    product = models.ManyToManyField('Product', through='Shop_Product')

    def __str__(self):
        return self.city + ' ' + self.address


class Brand(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Product(models.Model):
    ITEM_SORT_CHOICES = [
        ('own', 'own'),
        ('acquired', 'acq')
    ]

    ITEM_TYPE_CHOICES = [
        ('product', 'pr'),
        ('service', 'sr')
    ]

    barcode = models.IntegerField()
    vendor_code = models.CharField(max_length=250)
    name = models.CharField(max_length=250)
    attribute_value = models.IntegerField()
    item_sort = models.CharField(max_length=8, choices=ITEM_SORT_CHOICES, default='own')
    item_type = models.CharField(max_length=7, choices=ITEM_TYPE_CHOICES, default='product')
    full_name = models.CharField(max_length=250)
    tax_rate = models.IntegerField()
    description = models.TextField()
    preview = models.ImageField(upload_to='preview/%Y/%m/%d', blank=True, null=True)
    available = models.BooleanField(default=False)
    on_sale_soon = models.BooleanField(default=False)
    category = models.ManyToManyField('Category', related_name='Category')
    price = models.DecimalField(max_digits=5, decimal_places=2)
    characteristic = models.ManyToManyField('ValueName', through='Value')
    top_sales = models.BooleanField(default=False)
    date = models.DateField(auto_now_add=True)
    brand = models.ForeignKey('Brand', on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class CallBack(models.Model):
    phone = models.IntegerField()


class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    body_review = models.TextField()
    rating = models.IntegerField()
    is_published = models.BooleanField(default=False)
    date_created = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('main:review', args=[self.product.id])

    class Meta:
        ordering = ['-date_created']


class Shop_Product(models.Model):
    shop = models.ForeignKey('Shop', on_delete=models.CASCADE)
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    number_products = models.IntegerField()


class Category(models.Model):
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name


class Stock(models.Model):
    name = models.CharField(max_length=250)
    logic = models.TextField(blank=True, null=True)
    date_start = models.DateField()
    date_finish = models.DateField()
    product = models.ManyToManyField('Product', related_name='stock_product')

    def __str__(self):
        return self.name


class ValueName(models.Model):
    category_id = models.ForeignKey(Category, on_delete=models.CASCADE)  # M2M
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name


class Value(models.Model):
    product_id = models.ForeignKey(Product, on_delete=models.CASCADE)
    value_type_id = models.ForeignKey(ValueName, on_delete=models.CASCADE, related_name='value')  # Value_name_id
    value = models.CharField(max_length=250)

    def save(self, *args, **kwargs):
        if self.value_type_id.category_id in self.product_id.category.all():
            super(Value, self).save(*args, **kwargs)
        else:
            raise ValidationError(('Недопустимая категория'))

    def __str__(self):
        return self.value


class VirtualOrder(models.Model):
    products = models.ManyToManyField('Product', related_name='virtual_order_products')
    phone = models.IntegerField()


class Order(models.Model):
    DELIVERY_METHOD = [
        ('self', 'Самовывоз'),
        ('delivery', 'Доставка')
    ]

    PAYMENT_METHOD = [
        ('cash', 'Наличными при получении'),
        ('card', 'Картой при получении')
    ]

    STATE_CHOICE = [
        ('complete', 'Выполнен'),
        ('cancel', 'Отменен'),
        ('wait', 'Ожидание'),
        ('accept', 'Принят')
    ]

    products = models.ManyToManyField('Product', through='Order_Product')
    phone = models.IntegerField()
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    delivery_method = models.CharField(max_length=30, choices=DELIVERY_METHOD)
    payment_method = models.CharField(max_length=30, choices=PAYMENT_METHOD)
    comment = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, default=None)
    email = models.CharField(max_length=200)
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    date = models.DateField(auto_now_add=True)
    state = models.CharField(max_length=30, choices=PAYMENT_METHOD, default='wait')

    def get_absolute_url(self):
        return reverse('cart:order_detail', args=[self.id])


class Order_Product(models.Model):
    order = models.ForeignKey('Order', on_delete=models.CASCADE)
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    number = models.IntegerField()

shop/cart/forms.py
from django import forms
from django.core.exceptions import ValidationError

from main.models import Order, VirtualOrder


class CartAddProductForm(forms.Form):
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)


class ComparisonAddProductForm(forms.Form):
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)


class FavoritesAddProductForm(forms.Form):
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)


class RecentlyViewedProductForm(forms.Form):
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)


class VirtualOrderForm(forms.ModelForm):
    class Meta:
        model = VirtualOrder
        fields = ('phone',)

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if len(str(phone)) != 12 or str(phone)[:3] != '375':
            raise ValidationError('Номер должен быть равен 12 символов и в формате 375**')
        return phone


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ['products', 'price', 'user', 'state']

shop/cart/views.py
from django.core.mail import send_mail
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST
from django.views.generic import CreateView, DetailView, ListView

from main.models import CallBack, Order, Order_Product, Product, VirtualOrder

from .cart import Cart
from .comparison import Comparison
from .favorites import Favorites
from .forms import (CartAddProductForm, ComparisonAddProductForm,
                    FavoritesAddProductForm, OrderForm,
                    RecentlyViewedProductForm, VirtualOrderForm)
from .recentlyviewed import RecentlyViewed


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect(request.META.get('HTTP_REFERER'))


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'update': True})
    return render(request, 'detail.html', {'cart': cart})


@require_POST
def comparison_add(request, product_id):
    comparison = Comparison(request)
    product = get_object_or_404(Product, id=product_id)
    form = ComparisonAddProductForm(request.POST)
    if form.is_valid():
        comparison.add(product=product)
    return redirect(request.META.get('HTTP_REFERER'))


def comparison_detail(request):
    comparison = Comparison(request)
    for item in comparison:
        item['update_quantity_form'] = ComparisonAddProductForm(initial={'update': True})
    return render(request, 'comparison.html', {'comparison': comparison})


def comparison_remove(request, product_id):
    comparison = Comparison(request)
    product = get_object_or_404(Product, id=product_id)
    comparison.remove(product)
    return redirect(request.META.get('HTTP_REFERER'))


@require_POST
def favorites_add(request, product_id):
    favorites = Favorites(request)
    product = get_object_or_404(Product, id=product_id)
    form = FavoritesAddProductForm(request.POST)
    if form.is_valid():
        favorites.add(product=product)
    return redirect(request.META.get('HTTP_REFERER'))


def favorites_detail(request):
    favorites = Favorites(request)
    for item in favorites:
        item['update_quantity_form'] = FavoritesAddProductForm(initial={'update': True})
    return render(request, 'favorites.html', {'favorites': favorites})


def favorites_remove(request, product_id):
    favorites = Favorites(request)
    product = get_object_or_404(Product, id=product_id)
    favorites.remove(product)
    return redirect(request.META.get('HTTP_REFERER'))


def recently_viewed(request, product_id):
    recently_viewed = RecentlyViewed(request)
    product = get_object_or_404(Product, id=product_id)
    form = RecentlyViewedProductForm(request.POST)
    if form.is_valid():
        recently_viewed.add(product=product)
    return redirect(request.META.get('HTTP_REFERER'))


def recently_viewed_detail(request):
    recently_viewed = RecentlyViewed(request)
    if len(recently_viewed) < 5:
        products = Product.objects.filter(top_sales=True)[:5]
        for product in products:
            recently_viewed.add(product=product)
    for item in recently_viewed:
        item['update_quantity_form'] = RecentlyViewedProductForm(initial={'update': True})
    return recently_viewed


class VirtualOrderCreate(CreateView):
    form_class = VirtualOrderForm
    template_name = 'virtualorder.html'
    success_url = '/'

    def form_valid(self, form):
        cart = Cart(self.request)
        products = Product.objects.filter(id__in=cart.get_all_products_id())
        order = VirtualOrder(phone=form.cleaned_data['phone'])
        order.save()
        order.products.set(products)
        cart.clear()
        return redirect(self.success_url)


class OrderCreate(CreateView):
    form_class = OrderForm
    template_name = 'order.html'
    success_url = '/'

    def form_valid(self, form):
        cart = Cart(self.request)
        order = form.save(commit=False)
        order.price = cart.get_total_price()
        if self.request.user.is_authenticated:
            order.user = self.request.user
        order = form.save()
        for i in cart.cart.items():
            product = Product.objects.get(id=i[0])
            Order_Product.objects.create(order=order, product=product, number=i[1]['quantity'])
        cart.clear()
        return redirect(order.get_absolute_url())

    def get_initial(self):
        if self.request.user.is_authenticated:
            self.initial.update({
                'phone': self.request.user.phone,
                'email': self.request.user.email,
                'name': self.request.user.username,
            })
        return super().get_initial()


@receiver(post_save, sender=Order)
def order_message(sender, **kwargs):
    send_mail(
        'Заказ',
        f'Ваш заказ принят на обработку, номер вашего заказа {kwargs["instance"].id}',
        'vitalikstain@inbox.ru',
        [kwargs["instance"].email],
    )


@require_POST
def call_back(request):
    CallBack.objects.create(phone=request._post['callback'])
    return redirect(request.META.get('HTTP_REFERER'))


class OrderDetail(DetailView):
    model = Order
    context_object_name = 'order'
    template_name = 'orderdetail.html'


class OrderList(ListView):
    context_object_name = 'orders'
    template_name = 'orderlist.html'

    def get_queryset(self):
        orders = Order.objects.filter(user=self.request.user)
        return orders

shop/cart/templates/comparison.html
{% extends "main_page.html" %}
{% load static %}

{% block content %}
<h1>Сравнение</h1>
<table class="comparison">
    <tr>
        <th>&nbsp;</th>
        {% for item in comparison %}
        {% with product=item.product %}

        <th>
            <table>
                <tr>
                    <td><a href="{% url 'cart:comparison_remove' product.id %}">Удалить</a></td>
                </tr>
                <tr>
                    <td>{{product.name}}</td>
                </tr>
                <tr>
                    <td>
                        <img src="{{ product.preview.url }}" width="100" height="60"></td>
                </tr>
            </table>
        </th>

        {% endwith %}
        {% endfor %}
    </tr>

    {% for category in comparison.get_categories %}
    {% for valuename in category.valuename_set.all %}
    <tr>
        <td>{{valuename.name}}</td>
        {% for item in comparison %}
        {% with product=item.product %}
        {% if valuename.category_id in product.category.all %}
        <td>
            {% for value in product.value_set.all %}
            {% if value.value_type_id == valuename %}
            {{ value.value }}
        </td>
        {% else %}
        {% endif %}
        {% endfor %}
        {% else %}
        <td></td>
        {% endif %}
        {% endwith %}
        {% endfor %}
        {% endfor %}
    </tr>
    {% endfor %}

</table>
<p class="text-right">
    <a href="{% url 'main:main_page' %}" class="button light">В магазин</a>
</p>
{% endblock %}

shop/cart/templates/detail.html
{% extends "main_page.html" %}
{% load static %}

{% block content %}
<h1>Корзина покупок</h1>

{% for item in cart %}
{% with product=item.product %}
<table class="table_cart">
    <tr>
        <td>
            <img src="{{ product.preview.url }}" width="100" height="70">
        </td>
        <td><a href="{% url 'main:productdetail' product.id %}">{{ product.name }}</a><br>
            <h3>{{ item.price }}</h3></td>
        <td>
            <form action="{% url 'cart:cart_add' product.id %}" method="post">
                {% csrf_token %}
                {{ item.update_quantity_form.update }}
                <input type="submit" value="Добавить">
            </form>
        </td>
        <td class="num"><p>Количество {{ item.quantity }}</p>
            <p>Стоимость</p>
            <h3>{{ item.total_price }}</h3></td>
        <td><a href="{% url 'cart:cart_remove' product.id %}">Удалить</a></td>

    </tr>
</table>
{% endwith %}
{% endfor %}
<p class="text-right">
    <a href="{% url 'main:main_page' %}" class="button light">В магазин</a>
    {% with total_items=cart|length %}
    {% if cart|length > 0 %}
    <a href="{% url 'cart:virtual_order' %}">Заказ в один клик</a>
    <a href="{% url 'cart:order' %}" class="button">Оформить заказ</a>
    {% endif %}
    {% endwith %}
</p>
{% endblock %}

shop/cart/templates/favorites.html
{% extends "main_page.html" %}
{% load static %}

{% block content %}
<h1>Желания</h1>
{% for item in favorites %}
{% with product=item.product %}

<a href="{% url 'cart:favorites_remove' product.id %}">Удалить</a>


<div>
    <img src="{{ product.preview.url }}" height="300" width="300" alt=""><br>
    <a href="{% url 'main:productdetail' product.id %}">{{ product.name }}</a><br>
    {% for category in product.category.all %}
    <a href="{% url 'main:catalog' category.id %}">{{ category }}</a>
    {% endfor %}

</div>

</div>

{% endwith %}
{% endfor %}

<p class="text-right">
    <a href="{% url 'main:main_page' %}" class="button light">В магазин</a>
</p>
{% endblock %}

shop/cart/templates/order.html
{% extends 'main_page.html' %}
{% block content %}
<h1>Оформление заказа</h1>
<div style="display: flex;">
    <div class="order_form">
        <table>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.as_table }}
                <tr>
                    <td>
                        <button>Подтвердить заказ</button>
                    </td>
                </tr>
            </form>
        </table>

    </div>
    <div style="float:right;">
        <button><a href="{% url 'cart:virtual_order' %}">Заказ в один клик</a></button>
        <p>Не хотите ничего заполнять? мы все сделаем за вас</p>
    </div>
</div>
<div>
    <h2>Ваш заказ</h2>
    <table class="table_cart">
        <tr>
            <th>&nbsp;</th>
            <th>&nbsp;</th>
            <th>Количество</th>
            <th>Цена</th>
            <th>Стоимость</th>
        </tr>
        {% for item in cart %}
        {% with product=item.product %}

        <tr>
            <td>
                <img src="{{ product.preview.url }}" width="100" height="70">
            </td>
            <td><a href="{% url 'main:productdetail' product.id %}">{{ product.name }}</a></td>
            <td class="num"><h3>{{ item.quantity }}</h3></td>
            <td><h3>{{ item.price }}</h3></td>
            <td>
                <h3>{{ item.total_price }}</h3></td>

        </tr>

        {% endwith %}
        {% endfor %}
    </table>
    <a href="{% url 'cart:cart_detail' %}">Вернуться в корзину</a>
</div>
{% endblock %}

shop/cart/templates/orderdetail.html
{% extends 'main_page.html' %}
{% block content %}
<h1>Спасибо за покупку</h1>
<table>
    <tr>
        <td><p>Наши операторы свяжутся с вами в ближайшее время для подтверждения заказа</p>
            <h4>Номер Вашего заказа {{order.id}}</h4></td>
    </tr>
    <tr>
        <td>Информация по оплате и доставке</td>
    </tr>
    <tr>
        <td>Дата заказа: {{order.date}}</td>
    </tr>
    <tr>
        <td><h4>Параметры заказа:</h4></td>
    </tr>
    <tr>
        <td>
            <table>
                <tr>
                    <td>E-mail:</td>
                    <td>{{order.email}}</td>
                </tr>
                <tr>
                    <td>Телефон:</td>
                    <td>{{order.phone}}</td>
                </tr>
                <tr>
                    <td>Имя:</td>
                    <td>{{order.name}}</td>
                </tr>
                <tr>
                    <td>Точка вывоза:</td>
                    <td>{{order.shop}}</td>
                </tr>
                <tr>
                    <td>Способ доставки:</td>
                    <td>{{order.delivery_method}}</td>
                </tr>
                <tr>
                    <td>Способ оплаты:</td>
                    <td>{{order.payment_method}}</td>
                </tr>
                <tr>
                    <td>Комментарий к заказу:</td>
                    <td>{{order.comment}}</td>
                </tr>
            </table>
        </td>
    </tr>
</table>
<div>
    <h2>Информация по заказу</h2>
    <table class="table_cart">
        <tr>
            <th>&nbsp;</th>
            <th>&nbsp;</th>
            <th>Количество</th>
            <th>Цена</th>
            <th>Стоимость</th>
        </tr>
        {% for item in order.order_product_set.all %}
        <tr>
            <td>
                <img src="{{ item.product.preview.url }}" width="100" height="70">
            </td>
            <td><a href="{% url 'main:productdetail' item.product.id %}">{{ product.name }}</a></td>
            <td class="num"><h3>{{ item.number }}</h3></td>
            <td><h3>{{ item.product.price }}</h3></td>
            <td>
                <h3>{{ item.product.price }}</h3></td>
        </tr>


        {% endfor %}
    </table>
</div>
<a href="{% url 'main:main_page' %}">Вернуться в магазин</a>
{% endblock %}

shop/cart/templates/orderlist.html
{% extends 'profile.html' %}
{% block user_info %}
<div>
    <h1>История заказов</h1>
    <table>
        {% for order in orders %}
        <tr>
            <td>Заказ №{{ order.id }} от {{ order.date }}</td>
            <td>Сумма к оплате {{ order.price }}</td>
            <td><a href="{{ order.get_absolute_url }}">Содержимое заказа</a></td>
            <td>{{ order.state }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

shop/cart/templates/virtualorder.html
{% extends 'main_page.html' %}
{% block content %}
<h1>Заказ в один клик</h1>
<form action="" method="Post">
    {% csrf_token %}
    {{ form.as_p }}
    <button>ok</button>
</form>
{% endblock %}