shop/account/urls.py
from django.contrib.auth import views
from django.urls import path

from .views import (ChangePassword, LoginUser, RegisterUser, UserDetail,
                    UserLogout)

app_name = 'account'

urlpatterns = [
    path('register/', RegisterUser.as_view(), name='register'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', UserLogout.as_view(), name='logout'),
    path('profile/', UserDetail.as_view(), name='profile'),
    path('changepassword/', ChangePassword.as_view(), name='changepassword'),
    path('password-change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),
]

shop/cart/urls.py
from django.urls import path

from .views import (OrderCreate, OrderDetail, OrderList, VirtualOrderCreate,
                    call_back, cart_add, cart_detail, cart_remove,
                    comparison_add, comparison_detail, comparison_remove,
                    favorites_add, favorites_detail, favorites_remove)

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('comparison/', comparison_detail, name='comparison_detail'),
    path('favorites/', favorites_detail, name='favorites_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('comparison_add/<int:product_id>/', comparison_add, name='comparison_add'),
    path('favorites_add/<int:product_id>/', favorites_add, name='favorites_add'),
    path('comparison_remove/<int:product_id>/', comparison_remove, name='comparison_remove'),
    path('favorites_remove/<int:product_id>/', favorites_remove, name='favorites_remove'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
    path('orderoneclick/', VirtualOrderCreate.as_view(), name='virtual_order'),
    path('order/', OrderCreate.as_view(), name='order'),
    path('orderdetail/<int:pk>/', OrderDetail.as_view(), name='order_detail'),
    path('order_list/', OrderList.as_view(), name='order_list'),
    path('call-back/', call_back, name='call_back')
]

shop/main/urls.py
from django.urls import path

from .views import (CatalogView, CategoryList, Main_page, ProductDetailView,
                    ReviewCreate, ReviewList, SearchListView)

app_name = 'main'

urlpatterns = [
    path('', Main_page.as_view(), name='main_page'),
    path('category/', CategoryList.as_view(), name='category'),
    path('category/<int:pk>', CatalogView.as_view(), name='catalog'),
    path('product/<int:pk>', ProductDetailView.as_view(), name='productdetail'),
    path('review/<int:pk>', ReviewList.as_view(), name='review'),
    path('reviewcreate/<int:pk>', ReviewCreate.as_view(), name='reviewcreate'),
    path('search/', SearchListView.as_view(), name='search')
]

shop/shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('account.urls')),
    path('api/', include('rest_api.urls')),
    path('cart/', include('cart.urls')),
    path('', include('main.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/account/models.py
from django.db import models

# Create your models here.

shop/account/forms.py
from django import forms
from django.core.exceptions import ValidationError

from main.models import Profile


class UserForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = Profile
        fields = ('username', 'first_name', 'email', 'phone')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if len(str(phone)) != 12 or str(phone)[:3] != '375':
            raise ValidationError('Номер должен быть равен 12 символов и в формате 375**')
        return phone


class UserEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('username', 'email', 'phone', 'address', 'send_message')

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if len(str(phone)) != 12 or str(phone)[:3] != '375':
            raise ValidationError('Номер должен быть равен 12 символов и в формате 375**')
        return phone

shop/account/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView

from main.models import Profile

from .forms import UserEditForm, UserForm


class RegisterUser(CreateView):
    form_class = UserForm
    template_name = 'register.html'
    success_url = '/'


class LoginUser(LoginView):
    template_name = 'login.html'

    def get_success_url(self):
        return '/'


class UserLogout(LoginRequiredMixin, LogoutView):
    template_name = 'logout.html'
    success_url_allowed_hosts = ('account:main_page',)


class UserDetail(DetailView):
    model = Profile
    context_object_name = 'user'
    template_name = 'profile.html'

    def get_context_data(self, *args, **kwargs):
        context = super(UserDetail, self).get_context_data(**kwargs)
        context['form'] = UserEditForm(instance=self.request.user)
        return context

    def get_object(self):
        user = self.request.user
        return user

    def post(self, request, *args, **kwargs):
        form = UserEditForm(request.POST, instance=self.request.user)
        if form.is_valid():
            form.save()
            return redirect(request.META.get('HTTP_REFERER'))
        return render(request, self.template_name, {'form': form})


class ChangePassword(PasswordChangeView):
    template_name = 'change_password.html'
    success_url = reverse_lazy('account:profile')

shop/account/templates/change_password.html
{% extends 'main_page.html' %}
{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    <table>{{ form.as_table }}</table>
    <button>OK</button>
</form>
{% endblock %}

shop/account/templates/login.html
{% extends 'main_page.html' %}
{% block content %}
<title>Login</title>
<h1>ВХОД В ЛИЧНЫЙ КАБИНЕТ</h1>
<table>
    <form action="" method="POST">
        {% csrf_token %}
        {{form.as_table}}
        <tr>
            <td><a href="{% url 'account:register' %}" class="button_login">Регистрация</a></td>
            <td><input class="button_login" type="submit" value="Войти"></td>
        </tr>
    </form>
</table>
{% endblock %}

shop/account/templates/logout.html
{% extends 'main_page.html' %}
{% block content %}
<title>Title</title>
<h1>Вы успешно вышли</h1>
<a href="{% url 'main:main_page' %}">Главная</a>
{% endblock %}

shop/account/templates/profile.html
{% extends 'main_page.html' %}
{% block content %}
<h1 style="margin-left: 5%">Персональный кабинет</h1>
<div class="block_userprofile">

    <div class="userprofile_menu">
        <ul>
            <li><a href="{% url 'account:profile' %}">Личные данные</a></li>
            <li><a href="{% url 'cart:order_list' %}">История заказов</a></li>
            <li><a href="{% url 'cart:favorites_detail' %}">Список желаний</a></li>
            <li><a href="">Лист ожидания</a></li>
        </ul>
    </div>
    {% block user_info %}
    <div>
        <form action="" method="POST">
            {% csrf_token %}
            <table>
                <tr>
                    <td><p>Имя: </p></td>
                    <td><p>{{form.username}}</p></td>
                </tr>
                <tr>
                    <td><p>E-mail: </p></td>
                    <td><p>{{form.email}}</p></td>
                </tr>
                <tr>
                    <td><a href="{% url 'account:changepassword' %}">Изменить пароль</a></td>
                </tr>
                <tr>
                    <td><p>{{form.send_message}}</td>
                    <td>Получать информацию о акциях, специальных ценах и выгодных прендложениях</p></td>
                </tr>
                <tr>
                    <td><p>Телефон:</p></td>
                    <td><p>{{form.phone}}</p></td>
                </tr>
                <tr>
                    <td><p>Адресс доставки: </p></td>
                    <td><p>{{form.address}}</p></td>
                </tr>
            </table>
            <input class="save_button" type="submit" value="Сохранить">
        </form>
    </div>
    {% endblock %}
</div>
{% endblock %}

shop/account/templates/register.html
{% extends 'main_page.html' %}
{% block content %}
<title>Title</title>
<h1>Регистрация</h1>

<div>
    <table>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_table }}
            <td><input class="button_login" type="submit" value="Зарегистрироваться"></td>
        </form>
    </table>
</div>
{% endblock %}