shop/account/urls.py
from django.contrib.auth import views
from django.urls import path

from .views import (ChangePassword, LoginUser, RegisterUser, UserDetail,
                    UserLogout)

app_name = 'account'

urlpatterns = [
    path('register/', RegisterUser.as_view(), name='register'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', UserLogout.as_view(), name='logout'),
    path('profile/', UserDetail.as_view(), name='profile'),
    path('changepassword/', ChangePassword.as_view(), name='changepassword'),
    path('password-change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),
]

shop/cart/urls.py
from django.urls import path

from .views import (OrderCreate, OrderDetail, OrderList, VirtualOrderCreate,
                    call_back, cart_add, cart_detail, cart_remove,
                    comparison_add, comparison_detail, comparison_remove,
                    favorites_add, favorites_detail, favorites_remove)

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('comparison/', comparison_detail, name='comparison_detail'),
    path('favorites/', favorites_detail, name='favorites_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('comparison_add/<int:product_id>/', comparison_add, name='comparison_add'),
    path('favorites_add/<int:product_id>/', favorites_add, name='favorites_add'),
    path('comparison_remove/<int:product_id>/', comparison_remove, name='comparison_remove'),
    path('favorites_remove/<int:product_id>/', favorites_remove, name='favorites_remove'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
    path('orderoneclick/', VirtualOrderCreate.as_view(), name='virtual_order'),
    path('order/', OrderCreate.as_view(), name='order'),
    path('orderdetail/<int:pk>/', OrderDetail.as_view(), name='order_detail'),
    path('order_list/', OrderList.as_view(), name='order_list'),
    path('call-back/', call_back, name='call_back')
]

shop/main/urls.py
from django.urls import path

from .views import (CatalogView, CategoryList, Main_page, ProductDetailView,
                    ReviewCreate, ReviewList, SearchListView)

app_name = 'main'

urlpatterns = [
    path('', Main_page.as_view(), name='main_page'),
    path('category/', CategoryList.as_view(), name='category'),
    path('category/<int:pk>', CatalogView.as_view(), name='catalog'),
    path('product/<int:pk>', ProductDetailView.as_view(), name='productdetail'),
    path('review/<int:pk>', ReviewList.as_view(), name='review'),
    path('reviewcreate/<int:pk>', ReviewCreate.as_view(), name='reviewcreate'),
    path('search/', SearchListView.as_view(), name='search')
]

shop/shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('account.urls')),
    path('api/', include('rest_api.urls')),
    path('cart/', include('cart.urls')),
    path('', include('main.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/main/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse


class Profile(AbstractUser):
    phone = models.IntegerField(unique=True, null=True)
    address = models.CharField(max_length=250, null=True, blank=True)
    send_message = models.BooleanField(default=False)


class Shop(models.Model):
    city = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    product = models.ManyToManyField('Product', through='Shop_Product')

    def __str__(self):
        return self.city + ' ' + self.address


class Brand(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Product(models.Model):
    ITEM_SORT_CHOICES = [
        ('own', 'own'),
        ('acquired', 'acq')
    ]

    ITEM_TYPE_CHOICES = [
        ('product', 'pr'),
        ('service', 'sr')
    ]

    barcode = models.IntegerField()
    vendor_code = models.CharField(max_length=250)
    name = models.CharField(max_length=250)
    attribute_value = models.IntegerField()
    item_sort = models.CharField(max_length=8, choices=ITEM_SORT_CHOICES, default='own')
    item_type = models.CharField(max_length=7, choices=ITEM_TYPE_CHOICES, default='product')
    full_name = models.CharField(max_length=250)
    tax_rate = models.IntegerField()
    description = models.TextField()
    preview = models.ImageField(upload_to='preview/%Y/%m/%d', blank=True, null=True)
    available = models.BooleanField(default=False)
    on_sale_soon = models.BooleanField(default=False)
    category = models.ManyToManyField('Category', related_name='Category')
    price = models.DecimalField(max_digits=5, decimal_places=2)
    characteristic = models.ManyToManyField('ValueName', through='Value')
    top_sales = models.BooleanField(default=False)
    date = models.DateField(auto_now_add=True)
    brand = models.ForeignKey('Brand', on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class CallBack(models.Model):
    phone = models.IntegerField()


class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    body_review = models.TextField()
    rating = models.IntegerField()
    is_published = models.BooleanField(default=False)
    date_created = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('main:review', args=[self.product.id])

    class Meta:
        ordering = ['-date_created']


class Shop_Product(models.Model):
    shop = models.ForeignKey('Shop', on_delete=models.CASCADE)
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    number_products = models.IntegerField()


class Category(models.Model):
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name


class Stock(models.Model):
    name = models.CharField(max_length=250)
    logic = models.TextField(blank=True, null=True)
    date_start = models.DateField()
    date_finish = models.DateField()
    product = models.ManyToManyField('Product', related_name='stock_product')

    def __str__(self):
        return self.name


class ValueName(models.Model):
    category_id = models.ForeignKey(Category, on_delete=models.CASCADE)  # M2M
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name


class Value(models.Model):
    product_id = models.ForeignKey(Product, on_delete=models.CASCADE)
    value_type_id = models.ForeignKey(ValueName, on_delete=models.CASCADE, related_name='value')  # Value_name_id
    value = models.CharField(max_length=250)

    def save(self, *args, **kwargs):
        if self.value_type_id.category_id in self.product_id.category.all():
            super(Value, self).save(*args, **kwargs)
        else:
            raise ValidationError(('Недопустимая категория'))

    def __str__(self):
        return self.value


class VirtualOrder(models.Model):
    products = models.ManyToManyField('Product', related_name='virtual_order_products')
    phone = models.IntegerField()


class Order(models.Model):
    DELIVERY_METHOD = [
        ('self', 'Самовывоз'),
        ('delivery', 'Доставка')
    ]

    PAYMENT_METHOD = [
        ('cash', 'Наличными при получении'),
        ('card', 'Картой при получении')
    ]

    STATE_CHOICE = [
        ('complete', 'Выполнен'),
        ('cancel', 'Отменен'),
        ('wait', 'Ожидание'),
        ('accept', 'Принят')
    ]

    products = models.ManyToManyField('Product', through='Order_Product')
    phone = models.IntegerField()
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    delivery_method = models.CharField(max_length=30, choices=DELIVERY_METHOD)
    payment_method = models.CharField(max_length=30, choices=PAYMENT_METHOD)
    comment = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, default=None)
    email = models.CharField(max_length=200)
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    date = models.DateField(auto_now_add=True)
    state = models.CharField(max_length=30, choices=PAYMENT_METHOD, default='wait')

    def get_absolute_url(self):
        return reverse('cart:order_detail', args=[self.id])


class Order_Product(models.Model):
    order = models.ForeignKey('Order', on_delete=models.CASCADE)
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    number = models.IntegerField()

shop/main/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Review


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['body_review', 'rating']

    def clean_rating(self):
        rating = self.cleaned_data['rating']
        if int(rating) > 5 or int(rating) < 1:
            raise ValidationError('Оценка должна быть от 1 до 5')
        return rating

shop/main/views.py
from datetime import datetime

from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Q
from django.shortcuts import render
from django.views.generic import CreateView, DetailView, ListView

from cart.forms import (CartAddProductForm, ComparisonAddProductForm,
                        FavoritesAddProductForm)
from cart.views import recently_viewed, recently_viewed_detail

from .forms import ReviewForm
from .models import Category, Product, Review


class Main_page(ListView):
    queryset = Product.objects.all()
    context_object_name = 'products'
    template_name = 'main_page.html'

    def get_context_data(self, **kwargs):
        context = super(Main_page, self).get_context_data(**kwargs)
        context['on_sale_soon'] = Product.objects.filter(on_sale_soon=True)[:5]
        context['novelties'] = Product.objects.filter(date=datetime.today(), on_sale_soon=False, available=True)[:5]
        context['favorites_product_form'] = FavoritesAddProductForm()
        context['recently_viewed'] = recently_viewed_detail(self.request)
        return context


class CategoryList(ListView):
    queryset = Category.objects.all()
    context_object_name = 'categories'
    template_name = 'category.html'


class CatalogView(ListView):
    context_object_name = 'products'
    template_name = 'catalog.html'
    paginate_by = 1

    def get_queryset(self):
        products = Product.objects.filter(category=self.kwargs['pk'])
        return products


class ProductDetailView(DetailView):
    model = Product
    context_object_name = 'product'
    template_name = 'productdetail.html'

    def get(self, request, *args, **kwargs):
        recently_viewed(request, kwargs['pk'])
        return super(ProductDetailView, self).get(request, *args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context['cart_product_form'] = CartAddProductForm()
        context['comparison_product_form'] = ComparisonAddProductForm()
        context['favorites_product_form'] = FavoritesAddProductForm()
        context['reviews'] = Review.objects.filter(product=self.kwargs['pk'], is_published=True)[:3]
        return context


class ReviewList(ListView):
    context_object_name = 'reviews'
    template_name = 'review.html'
    paginate_by = 3

    def get_context_data(self, *args, **kwargs):
        context = super(ReviewList, self).get_context_data(**kwargs)
        context['product_id'] = self.kwargs['pk']
        return context

    def get_queryset(self):
        products = Review.objects.filter(product=self.kwargs['pk'], is_published=True)
        return products


class ReviewCreate(CreateView):
    form_class = ReviewForm
    template_name = 'reviewcreate.html'

    def form_valid(self, form):
        product = Product.objects.get(id=self.kwargs['pk'])
        review = Review(user=self.request.user, product=product)
        form = self.form_class(self.request.POST, instance=review)
        return super().form_valid(form)


class SearchListView(ListView):
    template_name = 'search.html'
    model = Product

    def get(self, request, *args, **kwargs):
        context = {}
        question = request.GET.get('q')

        if question is not None:
            object_list = Product.objects.filter(Q(name__icontains=question), available=True).prefetch_related(
                'category')
            context['last_question'] = '?q=%s' % question
            context['len_products'] = len(object_list)
            context['categories'] = Category.objects.filter(Category__in=object_list).distinct()
            context['recently_viewed'] = recently_viewed_detail(self.request)

            current_page = Paginator(object_list, 5)

            page = request.GET.get('page')
            try:
                context['object_list'] = current_page.page(page)
            except PageNotAnInteger:
                context['object_list'] = current_page.page(1)
            except EmptyPage:
                context['object_list'] = current_page.page(current_page.num_pages)

        return render(request, self.template_name, context=context)

shop/main/templates/catalog.html
{% extends 'main_page.html' %}
{% block content %}
<div class="block_goods">
    {% for product in products %}
    <div>
        <img src="{{ product.preview.url }}" height="300" width="300" alt=""><br>
        <a href="{% url 'main:productdetail' product.id %}">{{ product.name }}</a><br>
        {% for category in product.category.all %}
        <a href="{% url 'main:catalog' category.id %}">{{ category }}</a>
        {% endfor %}
    </div>


    {% endfor %}
</div>
<div>
    <span>
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">{{page_obj.previous_page_number}}</a>
        {% endif %}

        <span>
            {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">{{page_obj.next_page_number}}</a>
        {% endif %}
    </span>
</div>
{% endblock %}

shop/main/templates/category.html
{% extends 'main_page.html' %}
{% block content %}
<ul>
    {% for category in categories %}
    <li><a href="{% url 'main:catalog' category.id %}">{{ category.name }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

shop/main/templates/main_page.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.js"></script>
    <title>Title</title>
</head>
<body>
<div class="header_inform"><p class="header_inform_text">Важная информация для зоны быстрого баннера</p></div>
<div class="user">
    {% if user.is_authenticated %}
    <a href="{% url 'account:profile' %}">{{ user }}</a>
    <a href="{% url 'account:logout' %}">Выход</a>
    {% else %}
    <a href="{% url 'account:register' %}">Регистрация</a>
    <a href="{% url 'account:login' %}">Войти в кабинет</a>
    {% endif %}
</div>
<table class="header_table">
    <tr>
        <td>
            <div class="header_logo">
                <a href="{% url 'main:main_page' %}"><img class="logo_img" src="{% static 'img/integral_logo.jpg' %}"
                                                          alt=""></a>
            </div>
        </td>
        <td>
            <div>
                <div>
                    <a href="#">О компании</a>
                    <a href="#">Оплата и доставка</a>
                    <a href="#">Гарантии</a>
                    <a href="#">Контакты</a>
                </div>
                <div class="div_search">
                    <form action="{% url 'main:search' %}">
                        <input class="search" type="search" name="q" minlength="1" placeholder="Поиск товаров">
                        <input class="button_search" type="submit" value="Найти">
                    </form>
                </div>
                <div>
                    <p style="margin: auto">Популярные запросы</p>
                </div>
            </div>
        </td>
        <td>
            <table>

                <tr>
                    <td>
                        <a href="{% url 'cart:cart_detail' %}">
                            <img class="cart_img" src="{% static 'img/cart.jpg' %}" width="100" height="60" alt="">
                            <div>
                                <h3 style="margin: auto">ВАША КОРЗИНА</h3>
                                {% with total_items=cart|length %}
                                {% if cart|length > 0 %}

                                <p style="margin: auto">В корзине {{ total_items }} товара, общая сумма
                                    ${{ cart.get_total_price }}</p>
                                {% else %}
                                <p style="margin: auto">Пока она пуста но это лекго исправить :)</p>
                                {% endif %}
                                {% endwith %}
                            </div>
                        </a>
                    </td>

                </tr>
                <form action="{% url 'cart:call_back' %}" method="post">
                    <tr>
                        {% csrf_token %}
                        <td><input class="cart_phone" type="search" name="callback" placeholder="(0XX)XXX-XX-XX"
                                   maxlength="12" minlength="12"></td>
                    </tr>
                    <tr>
                        <td><input class="cart_phone_button" type="submit" value="Перезвоните мне"></td>
                    </tr>
                </form>

            </table>
        </td>
    </tr>

</table>
{% block content%}
<div>
    <ul class="menu">
        <a href="{% url 'main:category' %}">Все разделы</a>
        <li><a href=#>ТЕЛЕФОНЫ</a>
            <div class="submenu">
                <p><a href=#>Sudmenu 1</a></p>
                <p><a href=#>Sudmenu 1</a></p>
                <p><a href=#>Sudmenu 1</a></p>
            </div>
        </li>
        <li><a href=#>ПЛАНШЕТЫ</a>
            <div class="submenu">
                <p><a href=#>Sudmenu 2</a></p>
                <p><a href=#>Sudmenu 2</a></p>
                <p><a href=#>Sudmenu 2</a></p>
            </div>
        </li>
        <li><a href=#>ТВ, Аудио, Видео</a>
            <div class="submenu">
                <p><a href=#>Sudmenu 3</a></p>
                <p><a href=#>Sudmenu 3</a></p>
                <p><a href=#>Sudmenu 3</a></p>
            </div>
        </li>
        <li><a href=#>БЫТОВАЯ ТЕХНИКА</a>
            <div class="submenu">
                <p><a href=#>Sudmenu 4</a></p>
                <p><a href=#>Sudmenu 4</a></p>
                <p><a href=#>Sudmenu 4</a></p>
            </div>
        </li>
    </ul>
</div>


</div>
<div class="name_block">
    <h2 style="float: left">НОВИНКИ</h2>
    <a style="float: right" href="#">Все</a>
</div>
<div class="block_goods">
    {% for product in novelties %}
    <div>
        <img src="{{ product.preview.url }}" height="300" width="300" alt=""><br>
        <a href="{% url 'main:productdetail' product.id %}">{{ product.name }}</a><br>
        {% for category in product.category.all %}
        <a href="{% url 'main:catalog' category.id %}">{{ category }}</a>
        {% endfor %}
        <div style="display: flex">
            <h3>{{ product.price }}</h3>
            <form action="{% url 'cart:cart_add' product.id %}" method="post" style="margin-left: auto;">
                {{ cart_product_form }}
                {% csrf_token %}
                <input class="button_search" type="submit" value="Купить">
            </form>
        </div>
    </div>
    {% endfor %}
</div>
<div class="name_block">
    <h2 style="float: left">СКОРО В ПРОДАЖЕ</h2>
    <a style="float: right" href="#">Все</a>
</div>
<div class="block_goods">
    {% for product in on_sale_soon %}
    <div>
        <img src="{{ product.preview.url }}" height="300" width="300" alt=""></br>
        <a href="{% url 'main:productdetail' product.id %}">{{ product.name }}</a><br>
        {% for category in product.category.all %}
        <a href="{% url 'main:catalog' category.id %}">{{ category }}</a>
        {% endfor %}
    </div>
    {% endfor %}
</div>


<div class="name_block">
    <h2 style="float: left">НЕДАВНО СМОТРЕЛИ</h2>
    <a style="float: right" href="#">Все</a>
</div>
<div class="block_goods">
    {% for i in recently_viewed %}
    <div>
        <img src="{{ i.product.preview.url }}" height="300" width="300" alt=""></br>
        <a href="{% url 'main:productdetail' i.product.id %}">{{ i.product.name }}</a><br>
        <h3>{{i.product.price}}</h3>

        {% with total_items=favorites %}
        {% if i.product.id in favorites.get_all_products_id %}
        <a href="{% url 'cart:favorites_detail' %}"><p style="margin: auto">Уже в желаниях</p></a>
        <a href="{% url 'cart:favorites_remove' i.product.id %}">Удалить</a>
        {% else %}
        <form action="{% url 'cart:favorites_add' i.product.id %}" method="POST">
            {{ favorites_product_form }}
            {% csrf_token %}
            <input type="submit" value="Желание">
        </form>
        {% endif %}
        {% endwith %}

    </div>
    {% endfor %}
</div>

{% endblock %}
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

shop/main/templates/productdetail.html
{% extends 'main_page.html' %}
{% block content %}
<div>
    <div style="float: left;">
        <h1>{{ product.name }}</h1>
        <img src="{{ product.preview.url }}" alt=""><br>
        <div>
            <ul>

                <li><a href="#" id="showDiv3">Описание</a></li>
                <li><a href="#" id="showDiv1">Характеристики</a></li>
                <li><a href="#">Вместе выгоднее</a></li>
                <li><a href="#" id="showDiv2">Отзывы</a></li>
                <li><a href="#">Серии и модификации</a></li>
            </ul>
        </div>


        <div class="add_product">
            <h2>{{ product.price }}</h2>
            {% if product.on_sale_soon %}
            <h3>Скоро в продаже</h3>
            {% else %}
            <form action="{% url 'cart:cart_add' product.id %}" method="post">
                {{ cart_product_form }}
                {% csrf_token %}
                <input class="button_search" type="submit" value="В корзину">
            </form>
            {% endif %}
            <div class="add_comparison_favorites">

                {% with total_items=favorites %}
                {% if product.id in favorites.get_all_products_id %}
                <a href="{% url 'cart:favorites_detail' %}"><p style="margin: auto">Уже в желаниях</p></a>
                <a href="{% url 'cart:favorites_remove' product.id %}">Удалить</a>
                {% else %}
                <form action="{% url 'cart:favorites_add' product.id %}" method="POST">
                    {{ favorites_product_form }}
                    {% csrf_token %}
                    <input type="submit" value="Желание">
                </form>
                {% endif %}
                {% endwith %}


                {% with total_items=comparison %}
                {% if product.id in comparison.get_all_products_id %}
                <a href="{% url 'cart:comparison_detail' %}"><p style="margin: auto">Уже в сравнениях</p></a>
                <a href="{% url 'cart:comparison_remove' product.id %}">Удалить</a>
                {% else %}
                <form action="{% url 'cart:comparison_add' product.id %}" method="POST">
                    {{ comparison_product_form }}
                    {% csrf_token %}
                    <input type="submit" value="Сравнение">
                </form>
                {% endif %}
                {% endwith %}
            </div>
        </div>
    </div>
    <div class="characteristics" id="div1" hidden>
        <table>
            {% for detail in product.characteristic.all %}
            <tr>
                <td>{{ detail.name }}</td>
                {% for i in detail.value.all %}
                {% if i.product_id == product %}
                <td>{{ i.value }}</td>
            </tr>
            {% endif %}
            {% endfor %}
            {% endfor %}
        </table>

    </div>
    <div id="div2" hidden>
        {% if reviews %}
        <table>
            {% for review in reviews %}
            <tr>
                <td>Имя:</td>
                <td><h2>{{ review.user }}</h2></td>
            </tr>
            <tr>
                <td>Отзыв:</td>
                <td><p>{{ review.body_review }}</p></td>
            </tr>
            <tr>
                <td>Оценка:</td>
                <td><p>{{ review.rating }}</p></td>
            </tr>

            {% endfor %}
            <tr>
                <td><a href="{% url 'main:review' product.id %}">Все</a></td>
            </tr>
        </table>
        {% else %}
        <h3>Пока нет ни одного отзыва</h3>
        {% if user.is_authenticated %}
        <a href="{% url 'main:reviewcreate' product.id %}">Оставить отзыв</a>
        {% else %}
        <a href="{% url 'account:login' %}">Только авторизованные пользователи могут оставлять отзывы</a>
        {% endif %}
        {% endif %}
    </div>
    <div id="div3" hidden>
        <table>
            <tr>
                <td>
                    <h3>{{ product.description }}</h3>
                </td>
            </tr>
        </table>
    </div>
</div>
{% endblock %}

shop/main/templates/review.html
{% extends 'main_page.html' %}
{% block content %}
<table>
    {% for review in reviews %}
    <tr>
        <td>Имя:</td>
        <td><p>{{ review.user }}</p></td>
    </tr>
    <tr>
        <td>Отзыв:</td>
        <td><p>{{ review.body_review }}</p></td>
    </tr>
    <tr>
        <td>Оценка:</td>
        <td><p>{{ review.rating }}</p></td>
    </tr>
    {% endfor %}
</table>
<div>
    <span>
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">{{page_obj.previous_page_number}}</a>
        {% endif %}

        <span>
            {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">{{page_obj.next_page_number}}</a>
        {% endif %}
    </span>
</div>
<div>
    {% if user.is_authenticated %}
    <a href="{% url 'main:reviewcreate' product_id %}">Оставить отзыв</a>
    {% else %}
    <a href="{% url 'account:login' %}">Только авторизованные пользователи могут оставлять отзывы</a>
    {% endif %}
</div>
{% endblock %}

shop/main/templates/reviewcreate.html
{% extends 'main_page.html' %}
{% block content %}
{% if user.is_authenticated %}
<table>
    <form action="" method="POST">
        {% csrf_token %}
        {{form.as_table}}
        <tr>
            <td>
                <button>Оставить отзыв</button>
            </td>
        </tr>
    </form>
</table>
{% else %}
<a href="{% url 'account:login' %}">Только авторизованные пользователи могут оставлять отзывы</a>
{% endif %}
{% endblock %}

shop/main/templates/search.html
{% extends 'main_page.html' %}
{% load bootstrap3 %}
{% block content %}
<h1 class="search_title">Каталог товаров</h1>
<div class="search_categories">
    <h2 style="margin-left: 10%">Найдено {{ len_products }} товара в категориях</h2>
    {% for category in categories %}
    <p>{{ category }}</p>
    {% endfor %}
</div>
<div class="search_goods">

    {% for product in object_list %}

    <table width="25%">
        <tr>
            <td><a href="{% url 'main:productdetail' product.id %}">{{ product.name }}</a><br></td>
        </tr>
        <tr>
            <td><img src="{{ product.preview.url }}" height="300" width="300" alt=""><br></td>
        </tr>
        <tr>
            <td><h2>{{product.price}}</h2></td>
        </tr>
    </table>

    {% endfor %}


</div>
{% bootstrap_pagination object_list url=last_question %}


<div class="name_block">
    <h2 style="float: left">НЕДАВНО СМОТРЕЛИ</h2>
    <a style="float: right" href="#">Все</a>
</div>
<div class="block_goods">
    {% for i in recently_viewed %}
    <div>
        <img src="{{ i.product.preview.url }}" height="300" width="300" alt=""></br>
        <a href="{% url 'main:productdetail' i.product.id %}">{{ i.product.name }}</a><br>
        <h3>{{i.product.price}}</h3>

        {% with total_items=favorites %}
        {% if i.product.id in favorites.get_all_products_id %}
        <a href="{% url 'cart:favorites_detail' %}"><p style="margin: auto">Уже в желаниях</p></a>
        <a href="{% url 'cart:favorites_remove' i.product.id %}">Удалить</a>
        {% else %}
        <form action="{% url 'cart:favorites_add' i.product.id %}" method="POST">
            {{ favorites_product_form }}
            {% csrf_token %}
            <input type="submit" value="Желание">
        </form>
        {% endif %}
        {% endwith %}

    </div>
    {% endfor %}
</div>

{% endblock %}